name: cinemapedia_local_database
description: >
  ?
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  animate_do: ^4.2.0
  card_swiper: ^3.0.1
  dio: ^5.9.0
  drift: ^2.30.1
  drift_flutter: ^0.2.8
  flutter:
    sdk: flutter
  flutter_dotenv: ^6.0.0
  flutter_riverpod: ^3.1.0
  go_router: ^17.0.1
  intl: ^0.20.2
  path_provider: ^2.1.5
  riverpod: ^3.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  drift_dev: ^2.30.1
  build_runner: ^2.10.5

flutter:
  uses-material-design: true
  assets:
    - .env
