name: toktik_app
description: "A Flutter application that replicates a vertical video scrolling experience similar to TikTok, featuring fullscreen video playback, interactive buttons, and smooth page transitions."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  animate_do: ^4.2.0
  flutter:
    sdk: flutter
  intl: ^0.20.2
  provider: ^6.1.5+1
  video_player: ^2.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/videos/
